const resList = [
  {
    id: "74363",
    name: "The Belgian Waffle Co.",
    cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
    locality: "Near Kalyani Bhawan",
    areaName: "Kasba",
    costForTwo: "₹200 for two",
    cuisines: ["Waffle", "Desserts", "Ice Cream"],
    avgRating: 4.7,
    veg: true,
    parentId: "2233",
    avgRatingString: "4.7",
    totalRatingsString: "5K+",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 1.2,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "1.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "112767",
    name: "Tea Junction",
    cloudinaryImageId: "77d2fffe27cd59af5045a102d08af522",
    locality: "Lake Road",
    areaName: "Ballygunge",
    costForTwo: "₹150 for two",
    cuisines: ["Beverages", "Snacks", "Desserts"],
    avgRating: 4.5,
    parentId: "4311",
    avgRatingString: "4.5",
    totalRatingsString: "5K+",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "45571",
    name: "Rang De Basanti Dhaba",
    cloudinaryImageId: "2083f9883ebf4e25972bb0f93984981c",
    locality: "E M Bypass",
    areaName: "E M Bypass",
    costForTwo: "₹300 for two",
    cuisines: [
      "North Indian",
      "Kebabs",
      "Mughlai",
      "Biryani",
      "Punjabi",
      "Desserts",
      "Tandoor",
      "Indian",
      "Beverages",
      "Snacks",
    ],
    avgRating: 4.4,
    parentId: "758",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 26,
      lastMileTravel: 2,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "379886",
    name: "The Brooklyn Creamery - Healthy Ice Cream",
    cloudinaryImageId: "b1b35780a9b1dfeb26d680506d494eaa",
    locality: "Bally Gunge",
    areaName: "South Kolkata",
    costForTwo: "₹200 for two",
    cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
    avgRating: 4.5,
    veg: true,
    parentId: "236673",
    avgRatingString: "4.5",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 22,
      lastMileTravel: 2.9,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "2.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "23938",
    name: "Domino's Pizza",
    cloudinaryImageId: "sffbrkxdzijmchxjcx4s",
    locality: "New Empire",
    areaName: "Ballygunge",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.6,
    parentId: "2456",
    avgRatingString: "4.6",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 30,
      serviceability: "SERVICEABLE",
      slaString: "30 mins",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "407661",
    name: "Burger King",
    cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    locality: "New Market",
    areaName: "Esplanade",
    costForTwo: "₹350 for two",
    cuisines: ["Burgers", "American"],
    avgRating: 4.2,
    parentId: "166",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 39,
      lastMileTravel: 7.5,
      serviceability: "SERVICEABLE",
      slaString: "35-40 mins",
      lastMileTravelString: "7.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "30490",
    name: "Baskin Robbins - Ice Cream Desserts",
    cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
    locality: "Shakespeare Sarani Road",
    areaName: "Elgin",
    costForTwo: "₹400 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.7,
    veg: true,
    parentId: "5588",
    avgRatingString: "4.7",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },

  {
    id: "3071",
    name: "Jai Hind Dhaba",
    cloudinaryImageId: "cdbdjcego1vt4reojqiy",
    locality: "Bhawanipur",
    areaName: "Bhawanipur",
    costForTwo: "₹500 for two",
    cuisines: [
      "North Indian",
      "Indian",
      "Tandoor",
      "Kebabs",
      "Punjabi",
      "Home Food",
      "Chinese",
    ],
    avgRating: 4.5,
    parentId: "1928",
    avgRatingString: "4.5",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 27,
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "8914",
    name: "Subway",
    cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
    locality: "Ruby",
    areaName: "East Kolkata Township",
    costForTwo: "₹350 for two",
    cuisines: ["Healthy Food", "Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 4.4,
    parentId: "2",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 26,
      lastMileTravel: 2,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "10369",
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "Tollygunge (241)",
    areaName: "Netaji Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 4.3,
    parentId: "721",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 41,
      lastMileTravel: 7.2,
      serviceability: "SERVICEABLE",
      slaString: "40-45 mins",
      lastMileTravelString: "7.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
];

export default resList;
